### ISSUE TITLE
把 highlight.png panel.png 加入 gitignore 更清真一些

### ISSUE THREAD

**Issue by specter119** [hosxy/Fcitx5-Material-Color#1]
如题
而且，我不开单行预览的话， fcitx5-rime 可以用的。

**Comment by hosxy** [comment]
大部分界面都是由这两个控制的，删掉会直接打回原形。
因为 fcitx5 目前没有图形界面的主题编辑器，考虑到更换配色方案时不用修改 theme.conf，所以theme.conf 里写死了用 highlight.png 和 panel.png 。实际上highlight.png 和 panel.png 并不是一个真正的图片，它俩都只是一个软连接而已，它俩链接的目标才是真正使用图片。

不支持 fcitx5-rime 是我README的不清楚(的确是我的锅)，其实我的意思是说 fcitx5-rime 不支持单行模式，已修改 README 的措辞了。

**Comment by specter119** [comment]
啊，我意思是 ln -sf 换了目标后，git status 里会显示修改，蓝儿，其实我并改啥。

**Comment by hosxy** [comment]
> 啊，我意思是 ln -sf 换了目标后，git status 里会显示修改，蓝儿，其实我并没改啥。

啊，我明白你的意思了，我来改下

**Comment by hosxy** [comment]
已修改，
这样就没有默认配色方案了，第一使用就必须手动 `ln -sf` 一下了。
