### ISSUE TITLE
在Ubuntu20.04+KDE+fcitx5环境下使用此主题存在颜色偏差

### ISSUE THREAD

**Issue by Dreamer-Fantasy** [hosxy/Fcitx5-Material-Color#14]
按照首页README教程手动安装后不做任何修改：
![blue-bar](https://user-images.githubusercontent.com/58366528/99882263-140ce400-2c5a-11eb-91ae-9ed7ac91a52d.png)
![pink-bar](https://user-images.githubusercontent.com/58366528/99882267-166f3e00-2c5a-11eb-8803-0abee56a7082.png)
观察发现输出的十六位进制颜色的后4位顺序两两颠倒：
![track-blue-bar](https://user-images.githubusercontent.com/58366528/99882299-520a0800-2c5a-11eb-982c-2abddb2b95cd.png)
![track-pink-bar](https://user-images.githubusercontent.com/58366528/99882301-533b3500-2c5a-11eb-92e5-094ede6ba2c4.png)
手动颠倒配置文件中`[InputPanel/Highlight]`和`[Menu/Highlight]`后四位后，主题颜色恢复正常：
![correct-blue-bar](https://user-images.githubusercontent.com/58366528/99882318-7a920200-2c5a-11eb-92c3-13f9958ce975.png)

**Comment by hosxy** [comment]
见 #6 
这是fcitx5的bug，现在修复了，但是ubuntu 20.04中fcitx5版本过低是没有修复的版本

**Comment by ayalhw** [comment]
@Dreamer-Fantasy 
please report it to Ubuntu

**Comment by Dreamer-Fantasy** [comment]
我在`launchpad.net`找到了Ubuntu官方维护的fcitx5：
[](https://launchpad.net/ubuntu/+source/fcitx5)
这里提供的最新fcitx5包组修复了此issue中提到的bug。下载并安装它们以更新Ubuntu20.04中的老版本fcitx5包组。
若安装过程中提示缺少`libjson-c5`，前往以下网址下载它：
[](https://launchpad.net/ubuntu/+source/json-c/)
希望可以帮到其它与我遭遇相同的Ubuntu20.04用户。

**Comment by ayalhw** [comment]
其实应该报给Ubuntu让他们更新或者backport的……

**Comment by Dreamer-Fantasy** [comment]
![image](https://user-images.githubusercontent.com/58366528/100412443-aa546600-30af-11eb-80e1-1d1ea447b1d7.png)
提了。
