### ISSUE TITLE
自定义配置的问题

### ISSUE THREAD

**Issue by a188037445** [hosxy/Fcitx5-Material-Color#19]
我是从 debian 的软件仓库中安装的，请问应该在哪修改配置呢？

在 /usr/share/... 目录下修改了 theme.conf 之后，如果软件包更新了，这里的文件内容就会被重置。

**Comment by hosxy** [comment]
如果你想修改的话，就不要用软件包管理器安装了
手动 git clone 到用户目录然后你就可以任意修改了

**Comment by a188037445** [comment]
好吧，那我重新 git clone 吧。
