### ISSUE TITLE
How to enable fcitx5-rime single line mode

### ISSUE THREAD

**Issue by imaojun** [hosxy/Fcitx5-Material-Color#2]
Fcitx5-rime project has closed this requirement and updated the code.

https://github.com/fcitx/fcitx5-rime/commit/f1c5f5c9f39ea330aff487eb53f49a1fefc4e8b9

So how to add fcitx5-rime single line mode in the configuration.

I tried to configure **config**, **default.custom.yaml**, **classicui.conf**  all have no effect.

**Comment by hosxy** [comment]
you should edit this file `~/.config/fcitx5/conf/rime.conf`, and add this code to it:
```
# 可用时在应用程序中显示预编辑文本
PreeditInApplicaation=True
```
please exit fcitx5, before you edit `~/.config/fcitx5/conf/rime.conf`

**Comment by imaojun** [comment]
@hosxy  Thx. It works.

However, in addition to modifying `~/.config/fcitx5/profile`  file need to exit fcitx5 first. You can directly modify other configuration files and then restart fcitx5.

If others have encountered this problem , can use this method to solve it. 

If the path is no **rime.conf** file, you can create it first by yourself.
