### ISSUE TITLE
About the font name used by Fcitx5-Material-Color.

### ISSUE THREAD

**Issue by hongyi-zhao** [hosxy/Fcitx5-Material-Color#20]
On Ubuntu 20.04, I noticed I've the following fonts:

```
werner@X10DAi:~$ fc-list -b|grep -i 'fullname:' | grep '.*DejaVuSansMono' | sort -u
	fullname: "DejaVuSansMono YaHei Nerd Font Bold"(s)
	fullname: "DejaVuSansMono YaHei Nerd Font Oblique"(s)
	fullname: "DejaVuSansMono YaHei NF"(s)
werner@X10DAi:~$ fc-list -b|grep -i 'family:' | grep '.*DejaVuSansMono Nerd Font Mono' | sort -u
	family: "DejaVuSansMono Nerd Font Mono"(s)
```
I want to know for setting the Fcitx5-Material-Color, which name should I use, the fullname of the font or the family name?

**Comment by hosxy** [comment]
maybe you can use gui(fcitx5-config-qt) to change font,like this
![深度截图_选择区域_20201212224852](https://user-images.githubusercontent.com/17108640/101986973-3aa7c300-3ccc-11eb-9e0d-0e598fc57ef5.png)

**Comment by hongyi-zhao** [comment]
Very strange, I also opened the GUI but can't find the font config panel shown above.

![image](https://user-images.githubusercontent.com/11155854/101999479-6a7cb800-3d18-11eb-939c-3113c8f3d6d5.png)

**Comment by hosxy** [comment]
> Very strange, I also opened the GUI but can't find the font config panel shown above.
> 
> ![image](https://user-images.githubusercontent.com/11155854/101999479-6a7cb800-3d18-11eb-939c-3113c8f3d6d5.png)

in  `Global Options`

**Comment by hongyi-zhao** [comment]
Still can't find it. See following:

![image](https://user-images.githubusercontent.com/11155854/102151929-f294c600-3eae-11eb-8583-61d81d779422.png)

**Comment by hosxy** [comment]
> Still can't find it. See following:
> 
> ![image](https://user-images.githubusercontent.com/11155854/102151929-f294c600-3eae-11eb-8583-61d81d779422.png)

why not try `Addons` ?

**Comment by hongyi-zhao** [comment]
Got it. Thanks a lot. Use either of the following two commands to do the trick:
```
$ fcitx5-config-qt  
$ fcitx5-configtool
```
![image](https://user-images.githubusercontent.com/11155854/102210578-5057fb00-3f0d-11eb-8362-d074840f8ee3.png)
