### ISSUE TITLE
建议说明arch系linux安装方式

### ISSUE THREAD

**Issue by feilongfl** [hosxy/Fcitx5-Material-Color#3]
arch系linux可以直接使用包管理器安装
`yay -S community/fcitx5-material-color`

安装后在fcitx设置菜单中,设置主题为下面这些之一即可.
- Material-Color-Brown
- Material-Color-Indigo
- Material-Color-Red
- Material-Color-Blue
- Material-Color-DeepPurple
- Material-Color-Pink
- Material-Color-Teal

![image](https://user-images.githubusercontent.com/10269596/78896202-ad5c0100-7aa2-11ea-8138-70cad23638d1.png)

单行模式需要手动设置.

**Comment by hosxy** [comment]
已增加
