### ISSUE TITLE
请问我应该如何设置回单行模式

### ISSUE THREAD

**Issue by PILIHU2022** [hosxy/Fcitx5-Material-Color#31]
我已经参考过Archwiki以及本仓库的README.md了，但是还是无法设置会单行模式，都在配置文件中写入了
`
# 可用时在应用程序中显示预编辑文本
PreeditInApplication=True
`
也重启过输入法，但是仍然无法生效

**Comment by aohanhongzhi** [comment]
我想设置成双行
