### ISSUE TITLE
能否把图片改大一些？

### ISSUE THREAD

**Issue by a188037445** [hosxy/Fcitx5-Material-Color#4]
我使用竖排候选列表，默认的输入框尺寸显得有点小，我把四周的边距改大了一点后发现高亮的背景图片覆盖不了输入框的边缘了。

下面是截图，可以看到输入框右边有个白边：
![Screenshot_20200724_184437](https://user-images.githubusercontent.com/46810417/88383813-ce402c00-cddd-11ea-9fb2-4d18b872979f.png)

**Comment by hosxy** [comment]
重构了一下主题，使用 16进制颜色替代了图片，我本地测试修复了这个问题，你可以自己测试一下

**Comment by a188037445** [comment]
可以了，谢谢！
