### ISSUE TITLE
在kubuntu系统中选中高亮都为绿色

### ISSUE THREAD

**Issue by lujimin** [hosxy/Fcitx5-Material-Color#6]
不知道是什么原因导致的，帮忙看下，多谢。
![Screenshot_20200803_101831](https://user-images.githubusercontent.com/9785063/89139941-dc771080-d572-11ea-8e14-5d22c7a0f3d5.png)

**Comment by lujimin** [comment]
看上去像是取了反色，我把紫色的配置文件改成绿色的就解决了，具体原因未知，不知道是否和主题有关系，我用的是默认主题，暗色调的。
[InputPanel/Highlight]
Color=#99C649

**Comment by lujimin** [comment]
> 看上去像是取了反色，我把紫色的配置文件改成绿色的就解决了，具体原因未知，不知道是否和主题有关系，我用的是默认主题，暗色调的。
> [InputPanel/Highlight]
> Color=#99C649

改成亮色调主题

**Comment by hosxy** [comment]
我主题里没有用这个绿色耶，有点奇怪
好像问题都是出在 非 Archlinux 上

**Comment by ayalhw** [comment]
Bug Report: https://github.com/fcitx/fcitx5/issues/65
Bug fix: https://github.com/fcitx/fcitx5/commit/bd83a9841e1dc3e7296174d32f5ee7655f680689
